#!/usr/bin/bash


# weka-ahavi-config - configure avahi
logger WEKA Starting weka-avahi-config

#set -x
source /etc/os-release

if [ -f /.version ]; then
	TYPE=wsa
	ISO_VERSION=$(cat /.version)
elif [ -f /.wms-version ]; then
	TYPE=wms
	ISO_VERSION=$(cat /.wms-version)
else
	echo "neither WSA or WMS, not configuring avahi"
	exit
fi


TXT_RECORD="ISO_version=\"$ISO_VERSION\" WEKA_Linux_version=\"$VERSION_ID\""

# get Service tag, etc.
SERVICE_TAG=$(dmidecode -s system-serial-number)
if [ "$SERVICE_TAG" == "Not Specified" ]; then
	SERVICE_TAG="None"
fi
TXT_RECORD="$TXT_RECORD SerialNumber=\"$SERVICE_TAG\""

BMC_IPv4=$(ipmitool lan print | grep "IP Address   " | cut -d: -f2 | tr -d '[:space:]')
if [ "$BMC_IPv4" == "" ]; then
	BMC_IPv4='None'
fi

RACADM=/opt/dell/srvadmin/sbin/racadm
if [ -x $RACADM ]; then
	NO_IPV6="::"
	# if it works, we're on a Dell or WEKApod
	$RACADM get idrac.CurrentIPv6 2>&1 > /dev/null
	if [ $? == 0 ]; then
		# we're on a Dell or WEKApod - take some notes
		eval $($RACADM get idrac.CurrentIPv6.Address1 | grep '^A')
		if [ "$Address1" != "$NO_IPV6" ] ; then
			BMC_IPv6=$Address1
		else
			BMC_IPv6='None'
		fi
		eval $($RACADM get idrac.CurrentIPv6.LinkLocalAddress | grep '^L')
		if [ "$LinkLocalAddress" != "$NO_IPV6" ] ; then
			BMC_IPv6_LL=$LinkLocalAddress
		else
			BMC_IPv6_LL='None'
		fi

	fi
fi

if [ -z ${BMC_IPv6+x} ]; then
	# check if BMC_IPv6 is set - if not, either racadm not installed/working or we're not on a Dell/WEKApod - it should be set to *something*
	BMC_IP="[$BMC_IPv4]"
else
	BMC_IP="[$BMC_IPv4, $BMC_IPv6, $BMC_IPv6_LL]"
fi

TXT_RECORD="$TXT_RECORD BMC_IP=\"$BMC_IP\""

if [ "$TYPE" == "wsa" ]; then
	weka status 2>&1 > /dev/null
	RETURN=$?
	if [ $RETURN == 100 ]; then
		WEKA_MODE="STEM"
	elif [ $RETURN == 127 ]; then
		WEKA_MODE="Not Installed"
	else
		WEKA_MODE="Clusterized"
	fi
	WEKA_VERSION=$(weka version | cut '-d ' -f2)
	if [ "$WEKA_VERSION" == "" ]; then
		WEKA_VERSION="None"
	fi
	TXT_RECORD="$TXT_RECORD WEKA_vers=\"$WEKA_VERSION\" WEKA_mode=\"$WEKA_MODE\""
fi



mkdir -p /etc/avahi/services
sed "s/WEKATYPE/$TYPE/" /etc/avahi/avahi-boilerplate.service | sed "s/WEKATEXT/$TXT_RECORD/" > /etc/avahi/services/weka.service

logger WEKA Finished weka-avahi-config
