#!/usr/bin/bash

#set -x

# weka-everyboot - do things that need to be done every time the server boots
logger WEKA Starting weka-everyboot

VERSION="unknown"
MOTD="Not a WMS or WSA"
# if a WSA, there will be a /.version file (WMS has a /.wms-version file)
if [ -f /.version ]; then
	VERSION=$(cat /.version)
	MOTD="Welcome to the Weka Software Appliance!"
else
	VERSION=$(cat /.wms-version)
	MOTD="Welcome to the Weka Management Server!"
fi

### other weka installation items

# configure firewall
firewall-cmd --set-default-zone=public  2>&1 > /dev/null # other options are set in the kickstart

if [ -f /.wms-version ]; then
	firewall-cmd --add-port 3000/tcp --add-port 8151/tcp --add-port 8090/tcp --add-port 443/tcp --add-port 80/tcp --add-port 5353/udp --permanent
	firewall-cmd --remove-port=14000-15000/tcp --permanent
	# add ports for ansible-install
	firewall-cmd --add-port 7860/tcp --add-port 8060/tcp --permanent
	firewall-cmd --reload
fi

# install motd
MOTD_FILE=/etc/motd.d/01-weka
echo $MOTD > $MOTD_FILE
echo >> $MOTD_FILE
echo "Version $VERSION" >> $MOTD_FILE
echo >> $MOTD_FILE

# configure Avahi to beacon our information

# weka-ahavi-config - configure avahi
source /etc/os-release

if [ -f /.version ]; then
	TYPE=wsa
	ISO_VERSION=$(cat /.version)
elif [ -f /.wms-version ]; then
	TYPE=wms
	ISO_VERSION=$(cat /.wms-version)
else
	echo "neither WSA or WMS, not configuring avahi"
	exit 0
fi

TXT_PRE="<txt-record value-format=\"text\">"
TXT_END="</txt-record>\n    "
TXT_RECORD="${TXT_PRE}ISO_version=\"$ISO_VERSION\"${TXT_END}"
TXT_RECORD="${TXT_RECORD}${TXT_PRE}WEKA_Linux_version=\"$VERSION_ID\"${TXT_END}"

# get Service tag, etc.
SERVICE_TAG=$(dmidecode -s system-serial-number)
if [ "$SERVICE_TAG" == "Not Specified" ]; then
	SERVICE_TAG="None"
fi
TXT_RECORD="$TXT_RECORD${TXT_PRE}SerialNumber=\"$SERVICE_TAG\"${TXT_END}"

#
# See if we can figure out the BMC IP addresses - both IPv4 and IPv6 (and link-local IPv6)
#
BMC_IPv4=$(ipmitool lan print | grep "IP Address   " | cut -d: -f2 | tr -d '[:space:]')
if [ "$BMC_IPv4" == "" ]; then
	BMC_IPv4='None'
fi

# Make sure the IPv6 link-local address is autoconfigured
#if [ -x $RACADM ]; then
#	logger "WEKA weka-everyboot checking for BMC IPv6 Autoconfig"
#        NO_IPV6="::"
#        # if it works, we're on a Dell or WEKApod
#        $RACADM get idrac.CurrentIPv6 2>&1 > /dev/null
#        if [ $? == 0 ]; then
#                # we're on a Dell or WEKApod - take some notes
#                eval $($RACADM get idrac.IPv6.AutoConfig | grep '^A')
#                eval $($RACADM get idrac.IPv6.Enable | grep '^E')
#
#                if [ "$AutoConfig" == "Disabled" ] ; then
#                        # enable autoconfig
#			logger "WEKA weka-everyboot Enabling BMC IPv6 Autoconfig"
#                        $RACADM set idrac.CurrentIPv6.AutoConfig Enabled
#			CHANGED=True
#		else
#			logger "WEKA weka-everyboot IPv6 AutoConfig was Enabled"
#                fi
#                if [ "$Enable" == "Disabled" ] ; then
#                        # enable ipv6
#			logger "WEKA weka-everyboot Enabling BMC IPv6"
#                        $RACADM set idrac.IPv6.Enable Enabled
#			CHANGED=True
#		else
#			logger "WEKA weka-everyboot IPv6 was Enabled"
#                fi
#		if [ ! -z ${CHANGED+x} ]; then
#			logger "WEKA weka-everyboot Sleeping for IPv6 Autoconfig"
#			sleep 60 # give it time to autoconfigure
#		fi
#        fi
#fi

RACADM=/opt/dell/srvadmin/sbin/racadm

if [ -x $RACADM ]; then
	NO_IPV6="::"
	# if it works, we're on a Dell or WEKApod
	$RACADM get idrac.CurrentIPv6 2>&1 > /dev/null
	if [ $? == 0 ]; then
		# we're on a Dell or WEKApod - take some notes
		eval $($RACADM get idrac.CurrentIPv6.Address1 | grep '^A')
		if [ "$Address1" != "$NO_IPV6" ] ; then
			BMC_IPv6=$Address1
		fi
		eval $($RACADM get idrac.CurrentIPv6.LinkLocalAddress | grep '^L')
		if [ "$LinkLocalAddress" != "$NO_IPV6" ] ; then
			BMC_IPv6_LL=$LinkLocalAddress
		fi

	fi
fi

BMC_IP="[$BMC_IPv4"

if [ ! -z ${BMC_IPv6+x} ]; then
	# check if BMC_IPv6 is set - if not, either racadm not installed/working or we're not on a Dell/WEKApod - it should be set to *something*
	BMC_IP="$BMC_IP,$BMC_IPv6"
fi
if [ ! -z ${BMC_IPv6_LL+x} ]; then
	BMC_IP="$BMC_IP,$BMC_IPv6_LL"
fi

BMC_IP="$BMC_IP]"


#BMC_IP=$(ipmitool lan print | grep "IP Address   " | cut -d: -f2 | tr -d '[:space:]')
#if [ "$BMC_IP" == "" ]; then
#	BMC_IP=Unknown
#fi

TXT_RECORD="$TXT_RECORD${TXT_PRE}BMC_IP=\"$BMC_IP\"${TXT_END}"

echo TXT record before if is $TXT_RECORD

if [ "$TYPE" == "wsa" ]; then
	weka status > /dev/null 2>&1 
	RETURN=$?
	while [ $RETURN == 2 ]; do
		echo "waiting for WEKA container(s) to start"
		sleep 10
		weka version > /dev/null 2>&1
		RETURN=$?
		if [ $RETURN == 8 ]; then	# no version set - big trouble
			logger 'ERROR - no WEKA version set - check for error messages'
			# fall through so we're not waiting here forever
		else
			weka status > /dev/null 2>&1 
			RETURN=$?
		fi
	done
	if [ $RETURN == 100 ]; then
		echo Setting STEM mode
		WEKA_MODE='"STEM"'
	elif [ $RETURN == 127 ]; then
		echo WEKA not installed
		WEKA_MODE='"Not Installed"'
	elif [ $RETURN == 8 ]; then
		echo ERROR installing WEKA
		echo Return code is $RETURN
		WEKA_MODE='"ERROR"'
	else
		echo WEKA is part of a cluster
		echo Return code is $RETURN
		WEKA_MODE='"Clusterized"'
	fi
	WEKA_VERSION=$(weka version | cut '-d ' -f2)
	if [ "$WEKA_VERSION" == "" ]; then
		WEKA_VERSION="None"
	fi
	TXT_RECORD="${TXT_RECORD}${TXT_PRE}WEKA_vers=${WEKA_VERSION}${TXT_END}"
        TXT_RECORD="${TXT_RECORD}${TXT_PRE}WEKA_mode=${WEKA_MODE}${TXT_END}"
	# fix it so we don't have many " chars...
	TXT_RECORD=$(echo $TXT_RECORD | tr \" \' )
	echo "TXT record is $TXT_RECORD"
fi

mkdir -p /etc/avahi/services
sed "s/WEKATYPE/$TYPE/" /etc/avahi/avahi-boilerplate.service | sed "s+WEKATEXT+$TXT_RECORD+" > /etc/avahi/services/weka.service

logger WEKA Finishing weka-everyboot
