#!/usr/bin/bash

# weka-firstboot - install weka on bootup of a new server, and configure misc items that can't be done in kickstart
# working dir should be /opt/wekabits   (if put in /opt/weka, it would be removed with wekawhacker)
logger WEKA Starting weka-firstboot

# if a WSA, there will be a /.version file (WMS has a /.wms-version file)
if [ -f /.version ]; then
	# install weka
	pushd /opt/weka-*
	./install.sh &> /root/weka-install-log.txt
	popd
	VERSION=$(cat /.version)
	MOTD="Welcome to the Weka Software Appliance!"
	TYPE=wsa
	if [ -d /opt/MLNX* ]; then
		pushd /opt/MLNX*
		yes | ./mlnxofedinstall
		modprobe -r rpcrdma ib_srpt ib_isert rdma_cm
		/etc/init.d/openibd restart
	fi
else
	VERSION=$(cat /.wms-version)
	MOTD="Welcome to the Weka Management Server!"
	TYPE=wms
fi

### other weka installation items

# configure firewall
firewall-cmd --set-default-zone=public  # other options are set in the kickstart

if [ "$TYPE" == "wms" ]; then
	firewall-cmd --add-port 3000/tcp --add-port 8151/tcp --add-port 8090/tcp --add-port 443/tcp --add-port 80/tcp --permanent
	#firewall-cmd --remove-port=14000-15000/tcp   # allow so WMS can port-forward 14000 to the cluster
	# add ports for ansible-install
	firewall-cmd --add-port 7860/tcp --add-port 8060/tcp --permanent
	firewall-cmd --reload
fi

# generate ssh keys
mkdir -p /root/.ssh
chmod 700 /root/.ssh
ssh-keygen -f /root/.ssh/${HOSTNAME}_root_id_rsa -C root@${HOSTNAME} -q -N ''

mkdir -p /home/weka/.ssh
chmod 700 /home/weka/.ssh
ssh-keygen -f /home/weka/.ssh/${HOSTNAME}_weka_id_rsa -C weka@${HOSTNAME} -q -N ''
chown -R weka:weka /home/weka/.ssh

RACADM=/opt/dell/srvadmin/sbin/racadm

# see if we need to enable IPv6 Autoconfiguration
if [ -x $RACADM ]; then
	logger "WEKA weka-firstboot checking for BMC IPv6 Autoconfig"
        NO_IPV6="::"
        # if it works, we're on a Dell or WEKApod
        $RACADM get idrac.CurrentIPv6 2>&1 > /dev/null
        if [ $? == 0 ]; then
                # we're on a Dell or WEKApod - take some notes
                eval $($RACADM get idrac.IPv6.Enable | grep '^E')
                if [ "$Enable" == "Disabled" ] ; then
                        # enable ipv6
			logger "WEKA weka-firstboot Enabling BMC IPv6"
                        $RACADM set idrac.IPv6.Enable Enabled
			CHANGED=True
			sleep 60   # have to give it time to enable and DHCP
		else
			logger "WEKA weka-firstboot IPv6 was Enabled"
		fi

		# check if we have an IPv6 address (static or DHCP)
		eval $($RACADM get idrac.CurrentIPv6.Address1 | grep '^A')
		if [ "$Address1" == "$NO_IPV6" ] ; then
			logger "WEKA weka-firstboot IPv6 not static or DHCP... ensuring autoconfigure"
			eval $($RACADM get idrac.CurrentIPv6.LinkLocalAddress | grep '^L')
			if [ "$LinkLocalAddress" != "$NO_IPV6" ] ; then
				# autoconfig might not be enabled...
				eval $($RACADM get idrac.IPv6.AutoConfig | grep '^A')

				if [ "$AutoConfig" == "Disabled" ] ; then
					# enable autoconfig
					logger "WEKA weka-firstboot Enabling BMC IPv6 Autoconfig"
					$RACADM set idrac.CurrentIPv6.AutoConfig Enabled
					CHANGED=True
					sleep 60   # have to give it time to enable and autoconfigure
				else
					logger "WEKA weka-firstboot IPv6 AutoConfig was Enabled"
				fi
			fi
                fi
        fi
fi

DCISM=$(ls /opt/wekabits/dcism* | head -1)
if [ -f "$DCISM" ]; then
	dnf install -y /opt/wekabits/dcism*
fi

# if it looks like we were installed via the weka os installer, notify the install server that we're up.
WEKA_INSTSALLER_F=/opt/wekabits/wmsip.txt
if [ -f $WEKA_INSTALLER_F ]; then
	INSTALL_SOURCE=$(cat /opt/wekabits/wmsip.txt)
	ipmiip=$(ipmitool lan print | sed -n -r "s/IP Address\s*:\s*//p")
	notifyurl="http://$INSTALL_SOURCE/notify?weka-firstboot-complete&_myIPMIip=$ipmiip"
	 result=$(curl "$notifyurl")
         echo "result from notify server $wmsip is  $result"
fi

# disable the systemd unit that starts this script so it never runs again
systemctl disable weka-firstboot.service

logger WEKA Finished weka-firstboot
